// Skills config — no percentage levels, just categories & tech badges
export const skills = [
  // Frontend
  { name: 'React',        category: 'Frontend',  icon: '⚛️',  color: 'from-cyan-500/20 to-blue-500/20',     border: 'border-cyan-500/30'    },
  { name: 'JavaScript',   category: 'Frontend',  icon: '🟨',  color: 'from-yellow-500/20 to-amber-500/20',  border: 'border-yellow-500/30'  },
  { name: 'Tailwind CSS', category: 'Frontend',  icon: '🎨',  color: 'from-teal-500/20 to-cyan-500/20',     border: 'border-teal-500/30'    },
  { name: 'Three.js',     category: 'Frontend',  icon: '🎯',  color: 'from-indigo-500/20 to-violet-500/20', border: 'border-indigo-500/30'  },
  { name: 'Vite',         category: 'Frontend',  icon: '⚡',  color: 'from-purple-500/20 to-pink-500/20',   border: 'border-purple-500/30'  },
  // Backend
  { name: 'Node.js',      category: 'Backend',   icon: '🟢',  color: 'from-green-500/20 to-emerald-500/20', border: 'border-green-500/30'   },
  { name: 'Express',      category: 'Backend',   icon: '🚂',  color: 'from-slate-500/20 to-gray-500/20',    border: 'border-slate-500/30'   },
  { name: 'MongoDB',      category: 'Backend',   icon: '🍃',  color: 'from-emerald-500/20 to-green-500/20', border: 'border-emerald-500/30' },
  { name: 'REST APIs',    category: 'Backend',   icon: '🔗',  color: 'from-blue-500/20 to-indigo-500/20',   border: 'border-blue-500/30'    },
  // AI / ML
  { name: 'Python',       category: 'AI / ML',   icon: '🐍',  color: 'from-blue-600/20 to-yellow-500/20',   border: 'border-blue-500/30'    },
  { name: 'TensorFlow',   category: 'AI / ML',   icon: '🧠',  color: 'from-orange-500/20 to-red-500/20',    border: 'border-orange-500/30'  },
  { name: 'OpenCV',       category: 'AI / ML',   icon: '👁️', color: 'from-violet-500/20 to-indigo-500/20', border: 'border-violet-500/30'  },
  { name: 'LangChain',    category: 'AI / ML',   icon: '⛓️', color: 'from-lime-500/20 to-green-500/20',    border: 'border-lime-500/30'    },
  // IoT
  { name: 'Raspberry Pi', category: 'IoT',       icon: '🖥️', color: 'from-red-500/20 to-rose-500/20',      border: 'border-red-500/30'     },
  { name: 'Arduino',      category: 'IoT',       icon: '🔌',  color: 'from-cyan-500/20 to-teal-500/20',     border: 'border-cyan-500/30'    },
  { name: 'MQTT',         category: 'IoT',       icon: '📡',  color: 'from-sky-500/20 to-blue-500/20',      border: 'border-sky-500/30'     },
];

export const skillCategories = ['All', 'Frontend', 'Backend', 'AI / ML', 'IoT'];

export const services = [
  {
    id: 'ai',
    icon: '🤖',
    title: 'AI Solutions',
    tagline: 'Intelligence at your fingertips',
    description: 'Custom AI assistants, computer vision pipelines, LLM integration, and intelligent automation systems tailored to your business needs.',
    features: [
      'Custom LLM-powered chatbots & assistants',
      'Computer vision & image recognition',
      'Voice interfaces & NLP pipelines',
      'AI workflow automation',
    ],
    tags: ['LLM', 'Computer Vision', 'NLP', 'Automation'],
    gradient: 'from-violet-600 to-indigo-600',
    glowColor: 'shadow-violet-500/20',
    borderColor: 'border-violet-500/30',
    bgColor: 'from-violet-500/10 to-indigo-500/5',
    accent: 'text-violet-400',
    dotColor: 'bg-violet-400',
  },
  {
    id: 'web',
    icon: '🌐',
    title: 'Full-Stack Web Apps',
    tagline: 'From MVP to production at scale',
    description: 'Production-ready MERN stack applications — from MVPs to scalable SaaS platforms with clean architecture and great UX.',
    features: [
      'React frontends with stunning animations',
      'REST & GraphQL API design',
      'MongoDB / PostgreSQL databases',
      'Auth, payments & third-party integrations',
    ],
    tags: ['React', 'Node.js', 'MongoDB', 'REST API'],
    gradient: 'from-cyan-500 to-blue-600',
    glowColor: 'shadow-cyan-500/20',
    borderColor: 'border-cyan-500/30',
    bgColor: 'from-cyan-500/10 to-blue-500/5',
    accent: 'text-cyan-400',
    dotColor: 'bg-cyan-400',
  },
  {
    id: 'iot',
    icon: '🔌',
    title: 'IoT & Robotics',
    tagline: 'Connecting the physical & digital world',
    description: 'Smart device ecosystems, sensor integrations, robotic control systems, and edge AI solutions for real-world automation.',
    features: [
      'Arduino & Raspberry Pi prototyping',
      'MQTT / WebSocket sensor networks',
      'Real-time dashboards & monitoring',
      'Edge AI & computer vision on hardware',
    ],
    tags: ['Arduino', 'Raspberry Pi', 'MQTT', 'Edge AI'],
    gradient: 'from-emerald-500 to-teal-600',
    glowColor: 'shadow-emerald-500/20',
    borderColor: 'border-emerald-500/30',
    bgColor: 'from-emerald-500/10 to-teal-500/5',
    accent: 'text-emerald-400',
    dotColor: 'bg-emerald-400',
  },
  {
    id: 'automation',
    icon: '⚡',
    title: 'Automation & Bots',
    tagline: 'Work smarter, not harder',
    description: 'Workflow automation, process optimization, API integrations, and custom bots that save time and dramatically reduce operational costs.',
    features: [
      'Python scripting & task automation',
      'Web scraping & data pipelines',
      'Telegram / Discord / Slack bots',
      'API integration & webhook handling',
    ],
    tags: ['Python', 'Scripting', 'Bots', 'Pipelines'],
    gradient: 'from-amber-500 to-orange-600',
    glowColor: 'shadow-amber-500/20',
    borderColor: 'border-amber-500/30',
    bgColor: 'from-amber-500/10 to-orange-500/5',
    accent: 'text-amber-400',
    dotColor: 'bg-amber-400',
  },
];
